(in-package #:hermes-daemon)

(defvar *max-username-length* 33)
(defvar *socket-path* #p"/var/run/hermes.sock")
(defvar *fingerprint* #(82 111 98 105 110))
(defvar *fingerprint-length* (length *fingerprint*))
(defvar *token-length* 128)
(defvar *user-tokens-path* #p"/etc/hermes/")
(defvar *storage-device-prefix* "sd")
(defvar *devices-folder* #p"/dev/")
(defvar *safe-ott-device-offset* (+ *fingerprint-length* *token-length*))
(defvar *safe-ott-user-offset* *token-length*)
(defvar *safe-ott-device-offset* (+ *fingerprint-length* *token-length*))
(defvar *safe-ott-user-offset* *token-length*)
